Adding WhenActivated functionality to Android ViewHolders
reactiveui/ReactiveUI pull request #2545
Opened 2020-10-01 04:12 UTC by clintonrocksmith

**What kind of change does this PR introduce?**
Introduces the WhenActivated functionality to the RecyclerViewHolders in Android and AndroidX.

**What is the current behavior?**
WhenActivated cannot be used in Android as it crashes if implemented.

**What is the new behavior?**
WhenActivated now behaves appropriately even when navigating forward as well as backward to other screens.  This will help reduce the chances of memory leaks.

**What might this PR break?**
Unsure, will need further testing.  I'm currently testing this implementation in our production app.  It will go through QA by next week (first week of October) and from there it should be safe to work.

**Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
I'll start working on some documentation for the website to describe how this works.

2020-10-01 15:39 UTC, cabauman requested changes
Looks good. For consistency, can you just name the handler method like the View event?
`OnViewDeAttachedToWindow -> OnViewDetachedFromWindow`

2020-10-01 20:58 UTC, glennawatson commented
Some recent splat changes have broken the build. Will fix today

2020-10-19 06:39 UTC, glennawatson approved these changes

2020-10-22 12:25 UTC, worldbeater commented on src/ReactiveUI.AndroidSupport/ReactiveRecyclerViewViewHolder.cs
> +            view.ViewDetachedFromWindow += OnViewDetachedToWindow;
Probably this should be `OnViewDetachedFromWindow`.

2020-10-22 12:42 UTC, merged