Update OAPH to skip initial value when deferring subscription
reactiveui/ReactiveUI pull request #2546
Opened 2020-10-01 13:30 UTC by Evangelink

**What kind of change does this PR introduce?**
Allow to not emit the initial value when deferring the subscription.

**What is the current behavior?**
If you subscribe to the property change it will emit a first default value.

**What is the new behavior?**
If you subscribe to the property change it will NOT emit a first default value.

**What might this PR break?**
As far as I can tell the biggest risk, and a risk I would be facing on some projects, is that to workaround this behavior I have used `Skip(1)` and if the first value is no longer emitted then the `Skip(1)` will skip the wrong value.

**Please check if the PR fulfills these requirements**
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Other information**:
Fix #2124

2020-10-01 20:48 UTC, glennawatson commented
I'll fix the build issues today.

2020-10-01 20:49 UTC, glennawatson requested changes

2020-10-01 20:49 UTC, glennawatson commented on src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
> +        internal /* for testing purposes */ IObservable<T> Source { get; }
I would just make this a XML style comment.

2020-10-01 20:51 UTC, Evangelink commented
It's weird, I am having the same issue locally (Win10 machine) but the issue was already present on a fresh clone and latest commit of main so I thought this was only a local configuration being wrong.

2020-10-01 20:53 UTC, glennawatson commented
It's due to recent changes in splat.

2020-10-01 20:55 UTC, Evangelink commented
Oh ok! Thanks! BTW, I have left a comment/question on the ticket this PR is trying to fix. Feel free to give me your opinion and if you want I can file a follow-up a PR (or add a commit to this one).

2020-10-01 20:57 UTC, glennawatson commented
Having the internal is fine. Makes the test easier.

2020-10-01 21:00 UTC, Evangelink commented
I was more thinking about this one:

> I was tempted to also give a go to the overload with the `Func` parameter but to have it having any value that means that the initial value should not be emitted right away (because in this case there is no need to take the `Func`, we can have the value directly) but only at the time where the subscription is made (i.e. inside the `Value` property). Would it make any sense?

2020-10-01 21:04 UTC, glennawatson commented
Having a func and delay evaluation was where I was wanting to go.

2020-10-01 21:07 UTC, glennawatson commented
If you go for that approach the existing overload can call the func one. And then you can just add the evaluation step when the observable gets connected.

2020-10-05 16:40 UTC, Evangelink commented
Remaining work:

- Fix API list file
- Add tests for `ToProperty` (not sure if I should add only a dummy test or do something more complex).

2020-10-05 16:41 UTC, Evangelink commented on src/ReactiveUI/ObservableForProperty/OAPHCreationHelperMixin.cs
> +            Func<TRet> getInitialValue,
All overloads have a non-optional `Func` parameter to avoid the runtime resolution error that would happen otherwise.

2020-10-05 16:43 UTC, Evangelink commented on src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs
> +            Func<T>? getInitialValue = null,
I have to declare an optional parameter to avoid having an overload with the `onChanging` parameter in another position.

2020-10-15 11:55 UTC, worldbeater commented
Probably worth updating API approval tests btw. Just copy-paste the `.received.txt` file contents into the `.approved.txt` file.

2020-10-15 11:57 UTC, Evangelink commented
@worldbeater Thanks! I was delaying this to get some feedback about the "new" API. I am still not able to properly build the project locally and it seems that I cannot access the CI build logs so I am a bit in the blur to provide a better PR.

2020-10-15 12:12 UTC, worldbeater commented
The changes look good overall. Happy to see they aren't breaking existing APIs :+1: 

Also, there is a lazy and a hacky way to build and test the core parts of the project if you can't install all the required frameworks — just cut the frameworks you don't have on your PC from the `<TargetFrameworks>` section in the `.csproj` files, build and test the project, and then do `git reset **/*.csproj` before committing. This is bad advice, but this would allow you to run API approval tests locally at least.

2020-10-15 12:22 UTC, Evangelink commented
I think there is an implicit breaking change in the sense where people wanting to avoid this first notification have rely on a `Skip(1)` (at least that's what I did) and so upgrading to the new version will cause the `Skip(1)` to skip the wrong notification.

I have installed all tools/frameworks and it doesn't work, doing some tests it seems to be linked to:

1. VS2019 Preview (seems to be ok with regular one)

2. This test `AutofacDependencyResolver_Should_Register_ReactiveUI_CreatesCommandBinding` keeps breaking but it doesn't seem related to my change.

2020-10-15 21:56 UTC, glennawatson approved these changes

2020-10-15 21:56 UTC, merged